[package]
name = "ortalab-fuzzer"
version = "0.1.0"
edition = "2024"

[dependencies]
ortalib = "1.0.0"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
yaml-rust = "0.4"